spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    driver-class-name: org.postgresql.Driver
    username: apple
    password:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
  security:
    user:
      password: 123456
      name: sandeep
server:
  servlet:
    context-path: /apidev
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8085/eureka
